version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "aiortc"  # https://github.com/whitphx/streamlit-webrtc/issues/37
      versions: ["1.1.x"]
