site_name: Streamlit-WebRTC
site_url: https://whitphx.github.io/streamlit-webrtc
theme:
  name: material

markdown_extensions:
  - pymdownx.snippets:
      base_path: ['./docs']
      check_paths: true
      # FastAPI's documentation is a great reference and it uses `mdx_include` for the same purpose, importing external snippets. ref: https://github.com/fastapi/fastapi/pull/3648
      # I think it's because `pymdownx.snippets` was not available or not announced to be supported at the moment,
      # however, currently `pymdownx.snippets` is officially documented by Material for MkDocs and
      # it has the compatible features to what FastAPI chose `mdx_include` for, which are importing regions and adjusting indentation levels,
      # so I think we can simply choose `pymdownx.snippets` now.

hooks:
  - docs/hooks/remove_trailing_line.py
